version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: prismaapi-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=prismaapi